services:
  localstack:
    container_name: localstack-dynamodb
    image: localstack/localstack:3.0
    ports:
      - "4566:4566"            # LocalStack Gateway
    environment:
      # LocalStack configuration
      - DEBUG=${DEBUG:-0}
      - SERVICES=dynamodb,cloudformation
      - PERSISTENCE=0          # Disable persistence for simplicity
      # AWS configuration
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    networks:
      - dynamodb-network

networks:
  dynamodb-network:
    driver: bridge