AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB Single Table Design for Multi-Entity Storage'

Parameters:
  TableName:
    Type: String
    Default: Bookstore
    Description: Name of the DynamoDB table
  
  Environment:
    Type: String
    Default: local
    AllowedValues: [local, dev, staging, prod]
    Description: Environment name

Resources:
  # Main DynamoDB Table with Single Table Design
  BookstoreTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST  # On-demand billing for simplicity
      
      # Primary Key Structure
      # PK = Partition Key (Entity Type + ID)
      # SK = Sort Key (Entity Type + Additional Info)
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: gsi1pk
          AttributeType: S
        - AttributeName: gsi1sk
          AttributeType: S
        - AttributeName: gsi2pk
          AttributeType: S
        - AttributeName: gsi2sk
          AttributeType: S
      
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      
      # Global Secondary Index 1 - For inverse lookups
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: gsi1pk
              KeyType: HASH
            - AttributeName: gsi1sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        
        # Global Secondary Index 2 - For additional access patterns
        - IndexName: GSI2
          KeySchema:
            - AttributeName: gsi2pk
              KeyType: HASH
            - AttributeName: gsi2sk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      
      # Point-in-time recovery
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      
      # Server-side encryption
      SSESpecification:
        SSEEnabled: true
      
      # Stream configuration for change data capture
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES
      
      Tags:
        - Key: Environment
          Value: !Ref Environment
        - Key: Purpose
          Value: SingleTableDesignPOC
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref BookstoreTable
    Export:
      Name: !Sub '${AWS::StackName}-TableName'
  
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt BookstoreTable.Arn
    Export:
      Name: !Sub '${AWS::StackName}-TableArn'
  
  StreamArn:
    Description: ARN of the DynamoDB stream
    Value: !GetAtt BookstoreTable.StreamArn
    Export:
      Name: !Sub '${AWS::StackName}-StreamArn'